### ISSUE TITLE
Suggested refactors for /src/ files

### ISSUE THREAD

**Issue by michaelcarter** [holidayextras/static-site-generator#14]
I've been using this afternoon to familiarise myself with some of the code from the various SSG-related repositories. I feel this repository's files could use some tests & refactoring
Given the small amount of code in here, it seems like a really good candidate to polish right up.

A prime example of where the current stuff is difficult to follow can be found in the `getPrismicContent.js` module:

``` javascript
const getPrismicContent = ( ) => {

  return ( files, metalsmith, done ) => {
    Object.keys( files ).forEach( file => {
      const pageData = files[file].prismic.page.results[0];
      files[file].pageData = pageData.data;
      Object.keys( pageData.data ).forEach( data => {
        if ( typeof pageData.data[data].json.value === 'string' ) {
          files[file].pageData[ data ] = pageData.data[data].json.value;
        }
        // Get the data from fetchLinks fragments to save the html
        if ( pageData.data[data].json && pageData.data[data].json.fragments ) {
          Object.keys( pageData.data[data].json.fragments ).forEach( child => {
            if ( typeof pageData.data[data].json.fragments[child].value === 'string' ) {
              const newName = child.replace( pageData.data[data].json.type + '.', '' );
              files[file].pageData[ data ][newName] = pageData.data[data].json.fragments[child].value;
            }
          } );
        }
        delete files[file].prismic.page.results[0].data[data].json;
      } );
      files[file].pagename = file;
    } );
    return done( );
  };
};

export default getPrismicContent;
```

There's a lot going on here in just a few lines of code. The nested anonymous functions are making things difficult to interpret and I find myself having to derive _what_ the code is doing by understanding _how_ the code is working, rather than being able to see _what_ the code is doing without needing to dive into the details of _how_ it's doing that (which is arguably preferable).

From an outsiders perspective, a bit more [clarity over brevity](https://github.com/holidayextras/culture/blob/master/coding-principles.md#clarity-over-brevity) would be preferable here. I think it'd be great to see the code in this repo broken down into individual functions with names that succinctly explain what's going on within each module. That way, taking the above as an example, I can just read off the functions called within the module by the `getPrismicContent` exported function to figure out what it's doing, without having to dive into actual code too much.

**Comment by richardstevens** [comment]
Have addressed these issues now in https://github.com/holidayextras/static-site-generator/pull/22
